version: 2

models:
  - name: medicament
    description: "Drug specialties — one row per CIS code."
    columns:
      - name: cis
        description: "Code Identifiant Spécialité (primary key)"
        data_tests:
          - unique
          - not_null
      - name: denomination
        data_tests:
          - not_null
      - name: etat_commercialisation
        description: "Commercialization status (e.g. 'Commercialisée')"

  - name: presentation
    description: "Drug presentations (boxes) — one row per CIP code."
    columns:
      - name: cip13
        description: "13-digit CIP code (presentation identifier)"
        data_tests:
          - not_null
      - name: cis
        description: "FK → medicament.cis"
        data_tests:
          - not_null
          - relationships:
              to: ref('silver_bdpm__medicament')
              field: cis

  - name: composition
    description: "Active substances and excipients per drug specialty."
    columns:
      - name: cis
        data_tests:
          - not_null
          - relationships:
              to: ref('silver_bdpm__medicament')
              field: cis
      - name: nature_composant
        description: "SA = active substance, FT = pharmaceutical form"

  - name: substance
    description: "Unique active substances extracted from compositions."
    columns:
      - name: code_substance
        data_tests:
          - unique
          - not_null

  - name: groupe_generique
    description: "Generic drug groups."
    columns:
      - name: id_groupe
        data_tests:
          - unique
          - not_null

  - name: generique
    description: "Generic group memberships (CIS → groupe_generique)."
    columns:
      - name: cis
        data_tests:
          - not_null
      - name: type_generique
        description: "0=princeps, 1=générique, 2=générique par assimilation, 4=CPP"

  - name: condition_delivrance
    description: "Prescription and dispensing conditions per drug specialty."
    columns:
      - name: cis
        data_tests:
          - not_null

  - name: info_importante
    description: "Important safety information and RCP/notice links."
    columns:
      - name: cis
        data_tests:
          - not_null

  - name: interaction
    description: "Drug interactions from ANSM Thésaurus."
    columns:
      - name: substance_a
        data_tests:
          - not_null
      - name: substance_b
        data_tests:
          - not_null
      - name: niveau_contrainte
        description: >
          Constraint level: 'Contre-indication', 'Association déconseillée',
          'Précaution d''emploi', 'A prendre en compte'
        data_tests:
          - not_null
          - accepted_values:
              values:
                - "Contre-indication"
                - "Association déconseillée"
                - "Précaution d'emploi"
                - "A prendre en compte"
                - "À prendre en compte"
